name: dart_backend
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  
dependencies:
  dart_dotenv: ^1.0.1
  shelf: ^1.4.0
  shelf_router: ^1.1.3
